version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: limitguard-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    # restart: always # Disabled to allow Fail-Open testing

    # Optional: Redis Commander for UI (Senior dev touch)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
